include:
  - project: eiseron/stack/ci
    file: /templates/phoenix.yml
    ref: v0.1.6
    inputs:
      app_name: afinados
  - project: eiseron/stack/ci
    file: /templates/preview-build.yml
    ref: v0.1.15
    inputs:
      app_name: afinados
      preview_zone: afinados.io
  - project: eiseron/stack/ci
    file: /templates/publish-docs.yml
    ref: v0.1.10
    inputs:
      site_repo: eiseron/afinados/afinados-site
      locale_map: '{"pt_BR":"src/docs","en":"src/en/docs"}'
  - project: eiseron/stack/ci
    file: /templates/release.yml
    ref: v0.1.17
    inputs:
      automation_ref: v0.5.3

stages:
  - lint
  - test
  - build
  - preview
  - publish
  - release
